medusa_site/attendance/urls.py
from django.conf.urls import url, include

import views

urlpatterns = [
    url(r'^overtime_list$', views.overtime_list, name="overtime_list"),
    url(r'^apply$', views.apply_overtime, name="apply_overtime"),
    url(r'^cancel_overtime$', views.cancel_overtime, name="overtime_cancel"),
    url(r'^leader_audit$', views.leader_audit_list, name="leader_audit"),
    url(r'^overtime_audit$', views.overtime_audit, name="overtime_audit"),
]

medusa_site/main/urls.py
from django.conf.urls import url, include

from .import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login$', views.login_view, name="login"),
    url(r'^logout$', views.logout_view, name="logout"),
]

medusa_site/medusa_site/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import main.urls
import attendance.urls
import takeleave.urls

urlpatterns = [
    url(r'^', include(main.urls)),
    url(r'^attendance/', include(attendance.urls)),
    url(r'^takeleave/', include(takeleave.urls)),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

medusa_site/attendance/models.py
from django.db import models
from django.contrib.auth.models import User

class Department(models.Model):
  name = models.CharField(max_length=100)
  ordering = models.IntegerField()

  def __unicode__(self):
    return self.name


class OvertimeEntry(models.Model):
  user = models.ForeignKey(User)
  department = models.ForeignKey(Department)
  status = models.IntegerField()
  start_time = models.DateTimeField()
  end_time = models.DateTimeField()
  reason = models.TextField()
  pub_date = models.DateTimeField()
  date_created = models.DateTimeField(auto_now_add=True)


class OvertimeApplyEntry(models.Model):
  user = models.ForeignKey(User)
  overtime = models.ForeignKey(OvertimeEntry)
  time = models.DateTimeField()
  date_created = models.DateTimeField(auto_now_add=True)

medusa_site/attendance/forms.py
from django import forms

def ApplyOvertimeForm(*args, **kwargs):
  from .models import Department
  department = list(Department.objects.order_by("-ordering"))
  choices = [(d.id, d.name) for d in department]


  class _ApplyOvertimeForm(forms.Form):
    department = forms.ChoiceField(choices=choices)
    start_time = forms.DateTimeField()
    end_time = forms.DateTimeField()
    reason = forms.CharField(widget= forms.Textarea)

  return _ApplyOvertimeForm(*args, **kwargs)

class OvertimeAuditForm(forms.Form):

  status = forms.ChoiceField(choices=[(1, 'OK'), (0, 'NO')])
  #reason = forms.CharField()

medusa_site/attendance/views.py
from datetime import datetime
from django.http import JsonResponse, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.core.urlresolvers import reverse as reverse_url
from django.core.paginator import Paginator
from django.utils import timezone
from utils.paginations import generate_pagination
from .models import OvertimeEntry
from main.models import StaffRelatedEntry

from django.shortcuts import render
from django.core.exceptions import PermissionDenied
from .forms import ApplyOvertimeForm, OvertimeAuditForm
from .queries import get_user_overtime_queryset
from .consts import *


def status_to_text(status):
  if status == STATUS_WAIT:
    return u"審核中"

  if status == 1:
    return u"審核成功"

  if status == 2:
    return u"審核失敗"

  return "Nan"


def overtime_audit(request): 
  print "=" * 100
  print "method", request.method
  _id = int(request.GET["q"])
  entry = OvertimeEntry.objects.get(id=_id)

  if request.method == "POST":
    form = OvertimeAuditForm(request.POST)
    print "is_valid", form.is_valid()
    if form.is_valid():
      status = form.cleaned_data["status"]

      print "!!!> status", status
      if status == 1:
        entry.status = STATUS_SUCCESS
      else:
        entry.status = STATUS_REJECTED 
      entry.save()

      print "SUCCESS!!"

      return JsonResponse({"code": 0, "msg": u"簽核成功"})
    
    return JsonResponse({"code": 1, "msg": str(form.errors)})


  else:

    form = OvertimeAuditForm()

  return TemplateResponse(request, "attendance/overtime_audit.html", {
    "entry": entry,
    "form": form,
    })

def leader_audit_list(request):

  if not request.user.is_authenticated():
    raise PermissionDenied
  
  page_number = 1
  try:
    page_number = int(request.GET["p"])
  except:
    pass

  qs = get_user_overtime_queryset(request.user.id)


  pagination = generate_pagination(request, qs, 30)
  
  for obj in pagination.page.object_list:
     obj.minutes = round((obj.end_time - obj.start_time).total_seconds() / 60.0, 2)
     obj.status_name = status_to_text(obj.status)


  return TemplateResponse(request, "attendance/leader_audit.html", {
    "pagination": pagination,
    })


def overtime_list(request):

  if not request.user.is_authenticated():
    raise PermissionDenied

  page_number = 1
  try:
    page_number = int(request.GET["p"])
  except:
    pass
  
  qs = OvertimeEntry.objects
  qs = qs.filter(user=request.user.id).exclude(status=STATUS_CANCEL)
  qs = qs.order_by("-pub_date")

  pagination = generate_pagination(request, qs, 30)

  for obj in pagination.page.object_list:
    obj.minutes = round((obj.end_time - obj.start_time).total_seconds() / 60.0, 2)
    obj.status_name = status_to_text(obj.status)

  return TemplateResponse(request, "attendance/overtime_list.html", {
    "pagination": pagination, 
  })

def cancel_overtime(request):
  if request.user.is_authenticated():
    _id = int(request.GET["q"])

    try:
      entry = OvertimeEntry.objects.get(id=_id)
      if entry.user_id == request.user.id:
        entry.status = STATUS_CANCEL
        entry.save()
        return JsonResponse({
              "message": u"取消成功!",
              "code": 0,
          })
    except OvertimeEntry.DoesNotExist:
      pass

  #redirect_to = reverse_url("overtime_list")
  #return HttpResponseRedirect(redirect_to)
  return JsonResponse({
        "message": u"失敗",
        "code": 1,
    })

def apply_overtime(request):
  if not request.user.is_authenticated():
    raise PermissionDenied

  if request.method == "POST":
    form = ApplyOvertimeForm(request.POST)
    if form.is_valid():
      print "->" * 100
      start_time = form.cleaned_data["start_time"]
      end_time = form.cleaned_data["end_time"]
      reason = form.cleaned_data["reason"]
      department_id = form.cleaned_data["department"]

      #now = datetime.now()  1999.1.1 +08:00
      now = timezone.now()   # 1999.1.1 +00:00

      delta = end_time - start_time
      print "delta", delta
      entry = OvertimeEntry(
          user = request.user,
          department_id = department_id,
          start_time = start_time,
          end_time = end_time,
          status=STATUS_WAIT,
          reason=reason,
          pub_date=now,
          )
      entry.save()
      redirect_to = reverse_url("overtime_list")
      return HttpResponseRedirect(redirect_to)
  else:
    form = ApplyOvertimeForm()

  return render(request, 'attendance/apply_overtime.html', {
    "form": form,
    })

medusa_site/templates/attendance/apply_overtime.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui-timepicker-addon.css' %}" />

  <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-ui-timepicker-addon.js' %}"></script>
  <script type="text/javascript">
  $(function() {
     $("#id_start_time").datetimepicker();
     $("#id_end_time").datetimepicker();

  });
  
  </script>
{% endblock %}

{% block content %}

<h2>加班申請</h2>
<form action="" method="POST">
  {% csrf_token %}
<table style="background-color: #f2f2f2">
  {{ form.as_table }}
</table>

<input type="submit" value="OK"/>

</form>



{% endblock %}

medusa_site/templates/attendance/apply_takeleave.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquerey-ui.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquerey-ui.timepicker-addon.css' %}"/>

  <script type="text/javascript" src="{% static 'js/jqurery-ui.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jqurery-ui-timepicker-addon.js' %}"></script>
  <script type="text/javascript">
  $(function() {
    $("#id_start_time").datetimepicker();
    $("#id_end_time").datetimepicker();
  });
  
  
  </script>
{% endblock %}

{% block content %}

<h2>請假申請</h2>
<form action="" method="POST">
  {% csrf_token %}
<table style="background-color: #f2f2f2">
  {{ form.as_table }}
</table>
<input type="submit" value="OK"/>

</form>

{% endblock %}

medusa_site/templates/attendance/law_takeleave.html
    <div id="alert">
      <table>
  
        <h2>勞工請假規則 </h2>

        <dl>
          <dt>第 1 條  本規則依勞動基準法 (以下簡稱本法) 第四十三條規定訂定之。</dt>
          <dt>第 2 條  勞工結婚者給予婚假八日，工資照給。</dt>
          <dt>第 3 條  勞工喪假依左列規定：
            <dd>
            <dd>一、父母、養父母、繼父母、配偶喪亡者，給予喪假八日，工資照給。</dd>
            <dd>二、祖父母、子女、配偶之父母、配偶之養父母或繼父母喪亡者，給予喪假六日，工資照給。</dd>
            <dd>三、曾祖父母、兄弟姊妹、配偶之祖父母喪亡者，給予喪假三日，工資照給。</dd>
            </dd>
          </dt>
          <dt>第 4 條  勞工因普通傷害、疾病或生理原因必須治療或休養者，得在左列規定範圍內請普通傷病假：</dt>
            <dd>
              <dd>一、未住院者，一年內合計不得超過三十日。</dd>
              <dd>二、住院者，二年內合計不得超過一年。</dd>
              <dd>三、未住院傷病假與住院傷病假二年內合計不得超過一年。</dd>
              <dd>經醫師診斷，罹患癌症（含原位癌）採門診方式治療或懷孕期間需安胎休養者，其治療或休養期間，併入住院傷病假計算。</dd>
              <dd>普通傷病假一年內未超過三十日部分，工資折半發給，其領有勞工保險普通傷病給付未達工資半數者，由雇主補足之。</dd>
              <dd></dd>
            </dd>
          <dt>第 5 條  勞工普通傷病假超過前條第一項規定之期限，經以事假或特別休假抵充後仍未痊癒者，得予留職停薪。但留職停薪期間以一年為限。</dt>
          <dt>第 6 條  勞工因職業災害而致殘廢、傷害或疾病者，其治療、休養期間，給予公傷病假。</dt>
          <dt>第 7 條  勞工因有事故必須親自處理者，得請事假，一年內合計不得超過十四日。事假期間不給工資。</dt>
          <dt>第 8 條  勞工依法令規定應給予公假者，工資照給，其假期視實際需要定之。</dt>
          <dt>第 9 條  雇主不得因勞工請婚假、喪假、公傷病假及公假，扣發全勤獎金。</dt>
          <dt>第 10 條  勞工請假時，應於事前親自以口頭或書面敘明請假理由及日數。但遇有急病或緊急事故，得委託他人代辦請假手續。辦理請假手續時，雇主得要求勞工提出有關證明文件。</dt>
          <dt>第 11 條  雇主或勞工違反本規則之規定時，主管機關得依本法有關規定辦理。</dt>
          <dt>第 12 條  本規則自發布日施行。</dt>
        </dl>

      </table>
      
    </div>

medusa_site/templates/attendance/leader_audit.html
{% extends "base.html" %}

{% load static %}
{% block extra_head %}

  <link rel="stylesheet" type="text/css" href="{% static 'js/facebox/facebox.css' %}" />
  <script type="text/javascript" src="{% static 'js/facebox/facebox.js'%}"></script>

  <script type="text/javascript">
  $(function() 
    {


      $(".overtime-audit-link").facebox();

    $(".overtime-cancel-link").click(function(){
      var ok = confirm("確定要取消嗎?");
      var url = $(this).attr("href");

      if(ok) {
        $.get(url, function(rep){
          alert(rep.message);
            if(rep.code == 0) {
            window.location.reload();
            }
      });
     }
      return false;
    });
  });

  </script>
{% endblock %}

{% block content %}

<h2>加班簽核</h2>

<table>
  <thead>
    <tr>
      <th>姓名</th>
      <th>狀態</th>
      <th>開始時間</th>
      <th>結束時間</th>
      <th>分鐘</th>
      <th>原因</th>
      <th>簽核</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in pagination.page.object_list %}
    <tr>
      <td>{{ obj.user.username }}</td>
      <td>{{ obj.status_name }}</td>
      <td>{{ obj.start_time|date:'Y-m-d H:i:s' }}</td>
      <td>{{ obj.end_time|date:'Y-m-d H:i:s' }}</td>
      <td>{{ obj.minutes }}</td>
      <td>{{ obj.reason }}</td>
      <td>

        <a class="overtime-audit-link" href="{% url 'overtime_audit' %}?q={{ obj.id }}"><input type="checkbox"></a>

       
      </td>

    </tr>
  {% endfor %}
  </tbody>
</table>

<div class="pagination">
  {{ pagination.render }}
</div>

{% endblock %}

medusa_site/templates/attendance/overtime_audit.html
<!DOCTYPE html>
<html>
<head>
  <script type="test/javascript">
  $(function(){
      
    $("#overtime-audit-form").submit(function(){
      var url = $(this).attr("action");
      console.log(">>>Submit", url);
      var post_data = $(this).serialize();
      console.log(">>> post data", post_data);


      $.post(url, post_data, function(rep) {
        
        console.log(">>> post result", rep.code, rep.msg);
        alert(rep.msg);
        if(rep.code == 0) {
            window.location.reload();
        }
      });
      

      return false;
    });


  });
  </script>
</head>
<body>
  <h2>加班簽核</h2>

  
  <table id="table1" class="table-style1">
    <tr>
      <td>username</td>
      <td>{{ entry.user.username }}</td>
    </tr>
    <tr>
      <td>start time</td>
      <td>{{ entry.start_time|date:"Y-m-d H:i:s" }}</td>
    </tr>
    <tr>
      <td>end time</td>
      <td>{{ entry.end_time|date:"Y-m-d H:i:s" }}</td>
    </tr>
    <tr>
      <td></td>
      <td>

        <form id="overtime-audit-form" action="{% url 'overtime_audit' %}?q={{ entry.id }}" method="POST">       
          {% csrf_token %}
         {{ form.as_p }}

         <input type="submit">

        </form>
      
      </td>
    </tr>
  </table>
</body>
</html>

medusa_site/templates/attendance/overtime_list.html
{% extends "base.html" %}

{% block extra_head %}
  <script type="text/javascript">

  $(function() {
    
    $(".overtime-cancel-link").click(function(){

      var ok = confirm("確定要取消嗎?");
      var url = $(this).attr("href");

      if(ok) {
        $.get(url, function(rep) {
           alert(rep.message);
            if(rep.code == 0) {
               window.location.reload();
            }


        });


      }


       return false;
    });



  });
 </script>

 

{% endblock %}
 
{% block content %}


<h2>加班記錄</h2>
  <table>
    <thead>
      <tr>
        <th>姓名</th>
        <th>狀態</th>
        <th>開始時間</th>
        <th>結束時間</th>
        <th>分鐘</th>
        <th>原因</th>
        <th>取消</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in pagination.page.object_list %}
      <tr>
        <td>{{ obj.user.username }}</td>
        <td>{{ obj.status_name }}</td>
        <td>{{ obj.start_time|date:'Y-m-d H:i:s' }}</td>
        <td>{{ obj.end_time|date:'Y-m-d H:i:s' }}</td>
        <td>{{ obj.minutes }}</td>
        <td>{{ obj.reason }}</td>
        <td>

          <a class="overtime-cancel-link" href="{% url 'overtime_cancel' %}?q={{ obj.id }}"><input type="checkbox"></a>
        
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
<div class="pagination">
{{ pagination.render }}
</div>




{% endblock %}

medusa_site/templates/attendance/takeleave_audit.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}

  <link rel="stylesheet" type="text/css" href="{% static 'js/facebox/facebox.css' %}" />
  <script type="text/javascript" src="{% static 'js/facebox/facebox.js'%}"></script>

  <script type="text/javascript">
  $(function() 
    {


      $(".overtime-audit-link").facebox();

    $(".overtime-cancel-link").click(function(){
      var ok = confirm("確定要取消嗎?");
      var url = $(this).attr("href");

      if(ok) {
        $.get(url, function(rep){
          alert(rep.message);
            if(rep.code == 0) {
            window.location.reload();
            }
      });
     }
      return false;
    });
  });

  </script>
{% endblock %}



{% block content %}

<h2>出缺勤簽核</h2>
<table>
  <thead>
    <tr>
      <th>假別</th>
      <th>送簽者</th>
      <th>狀態</th>
      <th>開始時間</th>
      <th>結束時間</th>
      <th>分鐘</th>
      <th>原因</th>
      <th>簽核</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in pagination.page.object_list %}
    <tr>
      <td>{{ obj.category_name }}</td>
      <td>{{ obj.user.uaername }}</td>
      <td>{{ obj.status_name }}</td>
      <td>{{ obj.start_time|date:'Y-m-d H:i:s' }}</td>
      <td>{{ obj.end_time|date: 'Y-m_d H:i:s' }}</td>
      <td>{{ obj.minutes }}</td>
      <td>{{ obj.reason }}</td>
     
      <td><a class="takeleave-audit-link" href="{% url 'takeleave_audit' %}?q={{ obj.id }}"><input type="checkbox"></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<div class="pagination">
  {{ pagination.render }}
</div>

{% endblock %}

medusa_site/templates/attendance/takeleave_list.html
{% extends "base.html" %}
{% block extra_head %}
  <script type="text/javascript">
  $(function() {
    $(".takeleave-cancel-link").click(function(){
      var ok = confirm("Are you sure?");
      var url = $(this).attr("href");
      
      if(ok) {
        $.get(url, function(rep) {
          alert(rep.message);
          if(rep.code == 0) {
            window.location.reload();
          }
        });
      }
      return false;
    });
  });
  </script>
{% endblock %}
{% block content%}
<h2>出缺勤記錄</h2>
  <table>
    <thead>
      <tr>
        <th>假別</th>
        <th>狀態</th>
        <th>姓名</th>
        <th>部門</th>
        <th>開始時間</th>
        <th>結束時間</th>
        <th>分鐘</th>
        <th>原因</th>
        <th>取消</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in pagination.page.object_list %}
      <tr>
        <td>{{ obj.category_name }}</td>
        <td>{{ obj.status_name }}</td>
        <td>{{ obj.user.username }}</td>
        <td>{{ obj.department_name }}</td>
        <td>{{ obj.start_time|date:'Y-m-d H:i:s' }}</td>
        <td>{{ obj.end_time|date:'Y-m-d H:i:s' }}</td>
        <td>{{ obj.minutes }}</td>
        <td>{{ obj.reason }}</td>
        <td>
          <a class="takeleave-cancel-link" href="{% url 'takeleave_cancel' %}?q={{ obj.id }}"><input type="checkbox"></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
<div class="pagination">
  {{ pagination.render }}
</div>
{% endblock %}